# Generated by Django 5.1.6 on 2025-02-27 07:09

import apps.characters.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.characters.models.character_avatar_path,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("secret_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "display_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=6, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                        to_field="uid",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="characters__user_id_23fc58_idx"
                    ),
                    models.Index(
                        fields=["secret_key"], name="characters__secret__089882_idx"
                    ),
                    models.Index(
                        fields=["display_code"], name="characters__display_0169cf_idx"
                    ),
                ],
            },
        ),
    ]
