# Generated by Django 5.1.6 on 2025-02-27 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="display_url",
        ),
        migrations.AddField(
            model_name="character",
            name="display_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=6, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["display_code"], name="characters__display_0169cf_idx"
            ),
        ),
    ]
