# Generated by Django 5.1.6 on 2025-02-27 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="character",
            new_name="characters__user_ui_7cae2f_idx",
            old_name="characters__user_id_23fc58_idx",
        ),
        migrations.AlterField(
            model_name="character",
            name="user",
            field=models.ForeignKey(
                db_column="user_uid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to=settings.AUTH_USER_MODEL,
                to_field="uid",
            ),
        ),
    ]
