# Generated by Django 5.1.6 on 2025-02-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "characters",
            "0002_rename_characters__user_id_23fc58_idx_characters__user_ui_7cae2f_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status_type", models.CharField(max_length=50)),
                ("data", models.JSONField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色状态",
                "verbose_name_plural": "角色状态",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["character", "status_type", "timestamp"],
                        name="characters__charact_425c0c_idx",
                    )
                ],
            },
        ),
    ]
