# Generated by Django 5.1.6 on 2025-02-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_characterstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="status_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n    状态配置示例：\n    {\n        "vital_signs": {\n            "ele": {\n                "label": "当前电量",\n                "suffix": "%",\n                "color": {\n                    "type": "threshold",\n                    "rules": [\n                        {"value": 20, "color": "red"},\n                        {"value": 50, "color": "yellow"},\n                        {"default": "green"}\n                    ]\n                }\n            },\n            "temp": {\n                "label": "体温",\n                "suffix": "°C",\n                "color": {\n                    "type": "range",\n                    "rules": [\n                        {"min": 35, "max": 37.2, "color": "green"},\n                        {"min": 37.3, "max": 38, "color": "yellow"},\n                        {"default": "red"}\n                    ]\n                }\n            }\n        }\n    }\n    ',
            ),
        ),
    ]
