# Generated by Django 5.1.6 on 2025-02-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_character_status_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="avatar",
            field=models.URLField(
                blank=True, help_text="角色头像URL地址", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="status_config",
            field=models.JSONField(
                blank=True,
                default={
                    "display": {
                        "default_message": "还活着！",
                        "timeout_messages": [
                            {"hours": 24, "message": "怕不是似了"},
                            {"hours": 12, "message": "应该还活着..."},
                            {"hours": 6, "message": "可能睡着了"},
                            {"hours": 3, "message": "有一会没碰手机了"},
                        ],
                    },
                    "theme": {
                        "accent_color": "from-blue-400 to-purple-400",
                        "background_overlay": "from-gray-900/95 to-gray-800/95",
                        "background_url": "https://infinitypro-img.infinitynewtab.com/wallpaper/anime/408.jpg?imageView2/2/w/3200/format/webp/interlace/1",
                    },
                    "vital_signs": {
                        "status_1": {
                            "color": {
                                "rules": [
                                    {"color": "#ff0000", "value": 0},
                                    {"color": "#00ff00", "value": 100},
                                ],
                                "type": "threshold",
                            },
                            "description": "设备电量",
                            "key": "battery",
                            "label": "电量",
                            "suffix": "%",
                            "valueType": "number",
                        },
                        "status_2": {
                            "color": {
                                "rules": [
                                    {"color": "#ff0000", "value": 0},
                                    {"color": "#00ff00", "value": 100},
                                ],
                                "type": "threshold",
                            },
                            "description": "显示正在使用的APP",
                            "key": "phone",
                            "label": "正在使用",
                            "valueType": "text",
                        },
                        "status_3": {
                            "description": "所在城市",
                            "key": "location",
                            "label": "位置",
                            "valueType": "text",
                        },
                        "status_4": {
                            "description": "城市天气",
                            "key": "weather",
                            "label": "天气",
                            "valueType": "text",
                        },
                    },
                },
            ),
        ),
    ]
