# Generated by Django 5.1.6 on 2025-03-02 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0006_alter_character_status_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="WillConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("content", models.TextField(help_text="遗嘱内容")),
                (
                    "target_email",
                    models.EmailField(help_text="主要收件人邮箱", max_length=254),
                ),
                ("cc_emails", models.JSONField(default=list, help_text="抄送邮箱列表")),
                (
                    "timeout_hours",
                    models.IntegerField(default=168, help_text="触发时间（小时）"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="will_config",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "verbose_name": "遗嘱配置",
                "verbose_name_plural": "遗嘱配置",
                "indexes": [
                    models.Index(
                        fields=["character", "is_enabled"],
                        name="characters__charact_778e6e_idx",
                    )
                ],
            },
        ),
    ]
