# Generated by Django 5.1.6 on 2026-01-12 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_willconfig_cc_emails_alter_willconfig_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_public',
            field=models.BooleanField(default=False, help_text='是否在存活者列表公开显示'),
        ),
        migrations.AlterField(
            model_name='willconfig',
            name='timeout_hours',
            field=models.IntegerField(default=24, help_text='触发时间（小时）'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['is_public'], name='characters__is_publ_bec348_idx'),
        ),
    ]
