# Generated by Django 5.1.6 on 2026-01-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地理位置'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
    ]
