# Generated by Django 5.1.6 on 2026-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_message_location_alter_message_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='danmaku_ips_date',
            field=models.DateField(blank=True, help_text='IP列表对应的日期', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='danmaku_ips_today',
            field=models.JSONField(blank=True, default=list, help_text='今日已贡献经验的IP列表'),
        ),
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='角色总经验值'),
        ),
        migrations.AddField(
            model_name='character',
            name='last_sync_date',
            field=models.DateField(blank=True, help_text='上次同步日期', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='sync_streak',
            field=models.PositiveIntegerField(default=0, help_text='连续同步天数'),
        ),
    ]
