# Generated by Django 5.1.6 on 2026-04-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_add_experience_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='是否启用日报分析')),
                ('visibility', models.CharField(choices=[('private', '仅自己可见'), ('public', '所有人可见')], default='private', help_text='日报可见范围', max_length=20)),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text='字段映射关系，格式: {"phone_app": "状态key", "computer_app": "状态key", "steps": "状态key"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_config', to='characters.character')),
            ],
            options={
                'verbose_name': '日报配置',
                'verbose_name_plural': '日报配置',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='日报日期')),
                ('is_hidden', models.BooleanField(default=False, help_text='是否隐藏（隐藏后仅自己可见）')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='原始聚合数据')),
                ('analysis_result', models.JSONField(blank=True, default=dict, help_text='AI分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='characters.character')),
            ],
            options={
                'verbose_name': '日报',
                'verbose_name_plural': '日报',
                'ordering': ['-date'],
                'unique_together': {('character', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='dailyreportconfig',
            index=models.Index(fields=['character', 'is_enabled'], name='characters__charact_2f79b0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['character', '-date'], name='characters__charact_bbd758_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['character', 'date'], name='characters__charact_ed4404_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['date'], name='characters__date_0d9c31_idx'),
        ),
    ]
