# Generated by Django 5.1.6 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_daily_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='data_cutoff_time',
            field=models.DateTimeField(
                blank=True,
                help_text='数据截止时间（任务执行时的时间）',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='last_record_time',
            field=models.DateTimeField(
                blank=True,
                help_text='最新状态数据的时间，用于判断是否有新数据',
                null=True,
            ),
        ),
    ]
