# Generated by Django 5.1.6 on 2026-04-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_daily_report_add_time_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyreport',
            new_name='characters__charact_b4a2df_idx',
            old_name='characters__charact_bbd758_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyreport',
            new_name='characters__charact_38421b_idx',
            old_name='characters__charact_ed4404_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyreport',
            new_name='characters__date_7db023_idx',
            old_name='characters__date_0d9c31_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyreportconfig',
            new_name='characters__charact_b066fb_idx',
            old_name='characters__charact_2f79b0_idx',
        ),
        migrations.AddField(
            model_name='dailyreportconfig',
            name='persona',
            field=models.TextField(blank=True, default='', help_text='角色人设信息，用于LLM分析日报时作为背景参考，如：年龄、职业、日常习惯等', null=True),
        ),
    ]
