# Generated by Django 5.1.6 on 2026-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "characters",
            "0015_rename_characters__charact_bbd758_idx_characters__charact_b4a2df_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportconfig",
            name="system_inferred_persona",
            field=models.TextField(
                blank=True,
                default="",
                help_text="系统暗中生成的真实人设档案（不对用户展示），用于修正LLM的长期认知",
                null=True,
            ),
        ),
    ]
