# Generated by Django 5.1.6 on 2026-04-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0016_dailyreportconfig_system_inferred_persona"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportconfig",
            name="ai_persona",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='AI 人设配置，用于自定义日报分析时的 AI 身份，格式: {"core_identity": "核心身份", "personality_traits": "性格特征", "language_style": "语言风格"}',
            ),
        ),
    ]
