# Generated by Django 5.1.6 on 2026-04-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0017_dailyreportconfig_ai_persona"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonaHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="记录日期（每天一条）")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now=True, help_text="最后更新时间"),
                ),
                (
                    "persona_content",
                    models.TextField(
                        blank=True, default="", help_text="本次生成的侧写内容", null=True
                    ),
                ),
                (
                    "data_dates",
                    models.JSONField(
                        blank=True, default=list, help_text="本次侧写基于哪些日期的数据（日期列表）"
                    ),
                ),
                (
                    "is_first_time",
                    models.BooleanField(default=False, help_text="是否是首次生成侧写"),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, help_text="使用的 LLM 模型名称", max_length=100, null=True
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("scheduled", "定时任务"), ("manual", "手动触发")],
                        default="scheduled",
                        help_text="触发方式",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="关联的日报配置",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona_history",
                        to="characters.dailyreportconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "侧写历史记录",
                "verbose_name_plural": "侧写历史记录",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["config", "-date"],
                        name="characters__config__87a137_idx",
                    ),
                    models.Index(fields=["date"], name="characters__date_a5cc5b_idx"),
                ],
                "unique_together": {("config", "date")},
            },
        ),
    ]
