# Generated by Django 5.1.6 on 2026-05-02 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_personahistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='消息日期')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
                ('message_data', models.JSONField(help_text='消息数据')),
                ('message_type', models.CharField(help_text='消息类型（group/private）', max_length=20)),
                ('character', models.ForeignKey(help_text='关联的角色', on_delete=django.db.models.deletion.CASCADE, related_name='qq_messages', to='characters.character')),
            ],
            options={
                'verbose_name': 'QQ消息记录',
                'verbose_name_plural': 'QQ消息记录',
                'ordering': ['-date', '-timestamp'],
                'indexes': [models.Index(fields=['character', 'date'], name='characters__charact_1f2ac4_idx'), models.Index(fields=['character', 'message_type'], name='characters__charact_ab25ec_idx')],
            },
        ),
    ]
