# Generated by Django 5.1.6 on 2026-05-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0019_qqmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportantEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="事件所属日期")),
                (
                    "event_key",
                    models.CharField(help_text="同一日报内稳定去重 key", max_length=128),
                ),
                ("title", models.CharField(max_length=120)),
                ("summary", models.TextField()),
                ("event_type", models.CharField(blank=True, default="", max_length=50)),
                ("time_range", models.CharField(blank=True, default="", max_length=50)),
                (
                    "importance_score",
                    models.PositiveSmallIntegerField(
                        default=50, help_text="0-100，越高越重要"
                    ),
                ),
                ("confidence", models.FloatField(default=0.8, help_text="0-1，抽取可信度")),
                ("entities", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("evidence", models.JSONField(blank=True, default=list)),
                (
                    "source_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("embedding_text", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("milvus_synced", models.BooleanField(default=False)),
                ("milvus_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_events",
                        to="characters.character",
                    ),
                ),
                (
                    "source_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_events",
                        to="characters.dailyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "重要事件记忆",
                "verbose_name_plural": "重要事件记忆",
                "ordering": ["-date", "-importance_score"],
                "indexes": [
                    models.Index(
                        fields=["character", "-date"],
                        name="characters__charact_b90494_idx",
                    ),
                    models.Index(
                        fields=["character", "is_active", "-importance_score"],
                        name="characters__charact_b27979_idx",
                    ),
                    models.Index(
                        fields=["source_report"], name="characters__source__8e8158_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="characters__event_t_a5a6f5_idx"
                    ),
                ],
                "unique_together": {("character", "date", "event_key")},
            },
        ),
    ]
