# Generated by Django 5.1.6 on 2026-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0020_important_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportconfig",
            name="template_style",
            field=models.CharField(
                default="default", help_text="日报模板风格", max_length=50
            ),
        ),
    ]
