# Generated by Django 5.1.6 on 2026-05-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_dailyreportconfig_template_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportconfig',
            name='persona_updated_at',
            field=models.DateTimeField(blank=True, help_text='用户自述人设更新时间', null=True),
        ),
    ]
