# Generated by Django 5.1.6 on 2026-06-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0023_importantevent_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("ollama", "Ollama"), ("openai", "OpenAI 兼容")],
                        default="ollama",
                        help_text="嵌入服务类型",
                        max_length=20,
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        default="http://127.0.0.1:11434",
                        help_text="Ollama 形如 http://127.0.0.1:11434；OpenAI 兼容形如 https://api.openai.com/v1",
                        max_length=255,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OpenAI 兼容端点的密钥；Ollama 可留空。明文存储，请仅在受信任的自托管环境使用。",
                        max_length=255,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="nomic-embed-text",
                        help_text="嵌入模型名，如 nomic-embed-text / mxbai-embed-large / text-embedding-3-small",
                        max_length=100,
                    ),
                ),
                (
                    "dimensions",
                    models.PositiveIntegerField(
                        default=768,
                        help_text="向量维度。用于 Milvus 建表与 OpenAI dimensions 参数；pgvector 列不固定维度。⚠️ 改动维度/模型后必须点「重建向量」，否则旧向量与新查询维度不一致会导致检索失效。",
                    ),
                ),
                (
                    "max_chars",
                    models.PositiveIntegerField(
                        default=900, help_text="单条文本送入嵌入前的截断上限"
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(default=60, help_text="单次嵌入请求超时（秒）"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="关闭则停用语义检索，退回元数据兜底"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "嵌入模型配置",
                "verbose_name_plural": "嵌入模型配置",
            },
        ),
    ]
