# Generated by Django 5.1.4 on 2024-12-27 11:04

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="个人简介"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.users.models.avatar_upload_path,
                verbose_name="头像",
            ),
        ),
    ]
