# Generated by Django 5.1.4 on 2025-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_blacklisteduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklisteduser",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
