# Generated by Django 5.1.4 on 2025-01-11 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_blacklisteduser_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklisteduser",
            name="blocked_user",
            field=models.ForeignKey(
                db_column="blocked_user_uid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_by_users",
                to=settings.AUTH_USER_MODEL,
                to_field="uid",
            ),
        ),
        migrations.AlterField(
            model_name="blacklisteduser",
            name="user",
            field=models.ForeignKey(
                db_column="user_uid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blacklisted_users",
                to=settings.AUTH_USER_MODEL,
                to_field="uid",
            ),
        ),
    ]
